In [2]:
import pandas as pd

cols = ["product_name", "abbreviated_product_name", "generic_name", 
        "origins", "origins_tags", "origins_en", 
        "cities", "cities_tags", 
        "traces", "traces_tags", "traces_en", 
        "serving_size", "serving_quantity", "quantity", "product_quantity"]

pd.set_option("display.float_format", "{:.3f}".format)

df = pd.read_csv("en.openfoodfacts.org.products.csv", sep="\t", usecols=cols,  on_bad_lines="skip")

df.head()

C:\Users\De\AppData\Local\Temp\ipykernel_10032\3034165842.py:11: DtypeWarning: Columns (11,35,36,51,72) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("en.openfoodfacts.org.products.csv", sep="\t", usecols=cols,  on_bad_lines="skip")

,product_name,abbreviated_product_name,generic_name,quantity,origins,origins_tags,origins_en,cities,cities_tags,traces,traces_tags,traces_en,serving_size,serving_quantity,product_quantity
0,Limonade artisanale a la rose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,M&amp;M white,NaN,NaN,80 gram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80 gram,80.000,80.000
2,Chocolate n3,NaN,NaN,80 g,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.000
3,Pâte de fruits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Paleta gran reserva - Sierra nevada-,NaN,NaN,750ml,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5g,5.000,750.000

In [9]:
spalten_info = pd.DataFrame({"Anzahl Einträge": df.count(), "Einzigartige Werte": df.nunique(), "Datentyp": df.dtypes})
spalten_info["Anzahl Duplikate"] = spalten_info["Anzahl Einträge"] - spalten_info["Einzigartige Werte"]
pd.set_option("display.width", 1000)
pd.set_option("display.max_rows", None)

print(spalten_info)

                          Anzahl Einträge  Einzigartige Werte Datentyp  Anzahl Duplikate
product_name                      4166212             2614938   object           1551274
abbreviated_product_name            29368               26388   object              2980
generic_name                       184963              135437   object             49526
quantity                          1431579               74000   object           1357579
origins                            172617               25343   object            147274
origins_tags                       172505               19416   object            153089
origins_en                         172496               19274   object            153222
cities                                  1                   1   object                 0
cities_tags                        101856                8762   object             93094
traces                             171517               16777   object            154740
traces_tags                        233527               16950   object            216577
traces_en                          228341               16947   object            211394
serving_size                      1428571              129654   object           1298917
serving_quantity                  1407807                6721   object           1401086
product_quantity                  1377387                6708   object           1370679

In [10]:
temp = ["product_name", "abbreviated_product_name", "generic_name"]

print(df[temp].dropna().sample(30))

                                              product_name                 abbreviated_product_name                                       generic_name
2038978                           Lardons allumettes fumés             Pouce allumettes fumees 200g                           Lardons allumettes fumés
1724316             AUCHAN Amérique LatineEspresso sublimé      Auchan cafe amerique latine capsule  Capsules de café d'Amérique Latine, torréfié m...
1684980             Bénénuts Plaisir Brut Ananas à la noix        B&n pl brut ananas a la noix 120g  Mélange de noisettes, ananas déshydratés, rais...
1718828  Lustucru 2 gnocchi a poeler extra mozzarella t...              LT2 GAP MO TO 1A2E60% 280 L  Gnocchi à poêler fourré à la mozzarella et pur...
182962                                   Highland oatcakes                        Highland oatcakes                    Galettes d'avoine des Highlands
1933960                                   Rosette Cochonou          Coch ros ptr vpf ffam 130g c12p                                            Rosette
1735100                           Sardines au naturel 130g  Sardines au naturel 130g capitaine cook          Sardines au naturel - Préparées à la main
2139161                               Calmars persil & ail                     Calmars persil & ail                  Calmars cuits sauce persil et ail
1684634                   Lay's saveur fromage maxi format                   Lays fromage 360g recl   Chips de pommes de terre au fromage, aromatisées
1657836  Carlsberg 6X27,5CL CARLSBERG ELEPHANT 7.2 DEGR...              6x27,5cl carlsberg elephant                                              Bière
4200352  Elephant Mon Infusion Bio Digestion Légère 20 ...                  Eleph digest bio dc x20               Préparation aromatisée pour infusion
1907456                       Assortiment de biscuits 500g                  Assortiment de biscuits            Assortiment de biscuits 500g top budget
2040337                      Courges butternut en morceaux             Auchan courge butternut 600g             Courge butternut en morceaux, surgelée
2040938                       Cidre doux IGP Cidre Normand      A table en normandie cidre doux igp                            Cidre de Normandie doux
2041009                       Cidre doux igp cidre normand      A table en normandie cidre doux igp                            Cidre de normandie doux
1737123   BEURRE BIOLOGIQUE 1/2 SEL PQ 250g origine France     Beurre plaquette biologique demi-sel                                 Beurre Bio 1/2 Sel
1728549                        Sundae G caramel x4 - 150mL                        Sundae caramel x4                                     Sundae Caramel
2043506               Crousty Nuts**Croustillant noisettes         Auchan crousty nuts 6 x 25g 150g  Gaufrette fourrée (fourrage noisette 35,4%, fo...
2443121               Aptamil profutura duo advance 2 800g            Aptamil pf duo advance 2 800g                              Säuglingsmilchnahrung
2038926  Cuisine du Japon: Bœuf Teriyaki et nouilles au...              Auchan boeuf terriyaki 300g  Pâtes alimentaires cuites accompagnées de légu...
2041316                           100% pur jus - 3 agrumes         Auchan pur jus 3 agrumes rpet 1l  Jus de 3 agrumes avec pulpe, flash pasteurisé,...
2043845                  Haricots verts coupés - extra fin      Auchan haricots verts extra fins bo                   Haricots verts extra-fins coupés
1644374                                          Bledichef                     Bchef2x250 aub agnea  Plat à base de légumes et de viande adapté à b...
1729750                               Pizza 450g - chorizo                            Pizza chorizo                                      Pizza Chorizo
2040881                                        Briochettes              Auchan briochettes x12 480g                                  Briochette nature
1684262     Lay's 3D's Bugles goût fromage format familial      Lay's 3d's fromage 135g format fami        Produit soufflé à base de maïs goût fromage
4199953  Carte D'or Glace Saveur CheeseCake Caramel Sal...                Cdo 900ml caramel sel mer  Glace parfum cheesecake et glace caramel salé ...
1724219                                       BIO Noir 70%        Auchan bio chocolat noir 70% 100g  Chocolat noir 70% de cacao issu de l'agricultu...
2043300                    Cotons-tiges pour le maquillage      Auchan bâtonnets duo maquillage boi                    Cotons-tiges pour le maquillage
2039657                                    THÉ GLACÉ PÊCHE      Auchan boisson au the peche boite 3  Boisson aux extraits de thé aromatisée, saveur...

In [11]:
s1 = "product_name"
s2 = "abbreviated_product_name"
s3= "generic_name"

b1 = df[s1].isna()
b2 = df[s2].notna()
b3 = df[s3].notna()

anzahl = (b1 & (b2 | b3)).sum()

print(anzahl)

2910

In [12]:
s1 = "product_name"
s2 = "abbreviated_product_name"
s3= "generic_name"

b1 = df[s1].isna()
b2 = df[s2].notna()
b3 = df[s3].notna()

neu = df[(b1 & (b2 | b3))]

print(neu[[s1, s2, s3]].duplicated().sum())

223

In [13]:
df["product_name"] = df["product_name"].fillna(df["abbreviated_product_name"]).fillna(df["generic_name"])

drop_col = ["abbreviated_product_name", "generic_name"]

df = df.drop(columns=drop_col)

In [14]:
spalten_info = pd.DataFrame({"Anzahl Einträge": df.count(), "Einzigartige Werte": df.nunique(), "Datentyp": df.dtypes})
spalten_info["Anzahl Duplikate"] = spalten_info["Anzahl Einträge"] - spalten_info["Einzigartige Werte"]
pd.set_option("display.width", 1000)
pd.set_option("display.max_rows", None)

print(spalten_info)

                  Anzahl Einträge  Einzigartige Werte Datentyp  Anzahl Duplikate
product_name              4169122             2617310   object           1551812
quantity                  1431579               74000   object           1357579
origins                    172617               25343   object            147274
origins_tags               172505               19416   object            153089
origins_en                 172496               19274   object            153222
cities                          1                   1   object                 0
cities_tags                101856                8762   object             93094
traces                     171517               16777   object            154740
traces_tags                233527               16950   object            216577
traces_en                  228341               16947   object            211394
serving_size              1428571              129654   object           1298917
serving_quantity          1407807                6721   object           1401086
product_quantity          1377387                6708   object           1370679

In [15]:
temp = ["origins", "origins_tags", "origins_en"]

print(df[temp].dropna().sample(30))

                                                   origins                                       origins_tags                                         origins_en
1612438                                     United Kingdom                                  en:united-kingdom                                     United Kingdom
2647821                        Deutschland,Altes Land,Jork                   en:germany,de:altes-land,de:jork                      Germany,de:altes-land,de:jork
2149255                                             France                                          en:france                                             France
3381273           Pacific Ocean,West Central Pacific Ocean     en:pacific-ocean,en:west-central-pacific-ocean           Pacific Ocean,West Central Pacific Ocean
1792359                                    France,Volaille                              en:france,fr:volaille                                 France,fr:volaille
1004515                                             México                                          en:mexico                                             Mexico
2194988                                    Bretagne,France                              en:france,en:brittany                                    France,Brittany
3479510                                          fr:suisse                                     en:switzerland                                        Switzerland
550126                                              Turkey                                          en:turkey                                             Turkey
1684514                          France,Belgique,Allemagne                    en:france,en:germany,en:belgium                             France,Germany,Belgium
4151681                                        Netherlands                                     en:netherlands                                        Netherlands
1940908                                           Bretagne                              en:france,en:brittany                                    France,Brittany
3567712                                             Brasil                                          en:brazil                                             Brazil
1936376                                             France                                          en:france                                             France
3579804                                             Brasil                                          en:brazil                                             Brazil
2646152                                     France,Germany                               en:france,en:germany                                     France,Germany
1645582                                        Unspecified                                     en:unspecified                                        Unspecified
2154584                                             Italie                                           en:italy                                              Italy
1506886                                            Unknown                                         en:unknown                                            Unknown
1477526                                    France,Bretagne                              en:france,en:brittany                                    France,Brittany
2908940                                           Colombia                                        en:colombia                                           Colombia
1882149                    France,sunflower oil from Italy              en:france,en:sunflower-oil-from-italy                    France,Sunflower-oil-from-italy
1155113                                                USA                                   en:united-states                                      United States
1663432                                             France                                          en:france                                             France
2011316                                        Non indiqué                                     en:unspecified                                        Unspecified
1810899  Huile de tournesol de france,Graine de moutard...  fr:graine-de-moutarde-de-france,fr:huile-de-to...  fr:graine-de-moutarde-de-france,fr:huile-de-to...
1254970                                            Bolivia                                         en:bolivia                                            Bolivia
536363                                               Italy                                           en:italy                                              Italy
1914196                    France,Landes,sables des Landes           en:france,fr:landes,fr:sables-des-landes                 France,Landes,fr:sables-des-landes
1611346                                     United Kingdom                                  en:united-kingdom                                     United Kingdom

In [16]:
s1 = "origins"
s2 = "origins_tags"
s3= "origins_en"

b1 = df[s3].isna()
b2 = df[s2].notna()
b3 = df[s1].notna()

anzahl = (b1 & (b2 | b3)).sum()

print(anzahl)

132

In [17]:
s1 = "origins"
s2 = "origins_tags"
s3= "origins_en"

b1 = df[s3].isna()
b2 = df[s2].notna()
b3 = df[s1].notna()

temp = df[(b1 & (b2 | b3))]

print(temp[["origins", "origins_tags", "origins_en"]])

         origins origins_tags origins_en
19049          ?          NaN        NaN
126295         ?          NaN        NaN
355485         ?          NaN        NaN
439931      none      en:none        NaN
538940         ?          NaN        NaN
539096         ?          NaN        NaN
742043         ?          NaN        NaN
753749         ?          NaN        NaN
1208095        -          NaN        NaN
1208623        ?          NaN        NaN
1212188        ?          NaN        NaN
1222347        ?          NaN        NaN
1224317        ?          NaN        NaN
1225171        ?          NaN        NaN
1226339        ?          NaN        NaN
1232603        ?          NaN        NaN
1233981        ?          NaN        NaN
1234917        ?          NaN        NaN
1236696        ?          NaN        NaN
1246141        -          NaN        NaN
1248326        ?          NaN        NaN
1276704        ?          NaN        NaN
1282525        ?          NaN        NaN
1295923        ?          NaN        NaN
1340270        ?          NaN        NaN
1374923        ?          NaN        NaN
1392303        ?          NaN        NaN
1534269        ?          NaN        NaN
1588816        ?          NaN        NaN
1625489        -          NaN        NaN
1639299     ?, ?          NaN        NaN
1639525        ?          NaN        NaN
1640545        ?          NaN        NaN
1676398        ?          NaN        NaN
1742453        ?          NaN        NaN
1751045        ?          NaN        NaN
1768512        -          NaN        NaN
1769096        -          NaN        NaN
1773678        ?          NaN        NaN
1780387        ?          NaN        NaN
1819495        ?          NaN        NaN
1952036        ?          NaN        NaN
1984523        ?          NaN        NaN
1991076        ?          NaN        NaN
2010552        ?          NaN        NaN
2020125      ???          NaN        NaN
2023300       ??          NaN        NaN
2036351        ?          NaN        NaN
2045039        ?          NaN        NaN
2051198        ?          NaN        NaN
2056440        ?          NaN        NaN
2058799        ?          NaN        NaN
2082407        ?          NaN        NaN
2132073        ?          NaN        NaN
2143457        ?          NaN        NaN
2156081        ?          NaN        NaN
2229882        ?          NaN        NaN
2274973  en:None      en:none        NaN
2280991      NaN      en:none        NaN
2287547        ?          NaN        NaN
2324820        ?          NaN        NaN
2334693        ?          NaN        NaN
2352557        ?          NaN        NaN
2426416     none      en:none        NaN
2451046        ?          NaN        NaN
2453173        ?          NaN        NaN
2455674        ?          NaN        NaN
2507581     none      en:none        NaN
2529161        ?          NaN        NaN
2602200        -          NaN        NaN
2603994        -          NaN        NaN
2711799        ?          NaN        NaN
2721652        ?          NaN        NaN
2801350        ?          NaN        NaN
2829153        ?          NaN        NaN
2844497        ?          NaN        NaN
2864737     none      en:none        NaN
2870080        .          NaN        NaN
2981800        ?          NaN        NaN
2992734        ?          NaN        NaN
2992740        ?          NaN        NaN
2993804        ?          NaN        NaN
2994192        ?          NaN        NaN
2995922        ?          NaN        NaN
2997111        ?          NaN        NaN
2997426        ?          NaN        NaN
2997745        ?          NaN        NaN
3000285        ?          NaN        NaN
3007238        ?          NaN        NaN
3007247        ?          NaN        NaN
3007656        ?          NaN        NaN
3007816        ?          NaN        NaN
3008624        ?          NaN        NaN
3013905        ?          NaN        NaN
3024306        ?          NaN        NaN
3024795        ?          NaN        NaN
3025415        ?          NaN        NaN
3025516        ?          NaN        NaN
3026546        ?          NaN        NaN
3027298        ?          NaN        NaN
3027304        ?          NaN        NaN
3032315        ?          NaN        NaN
3041296        /          NaN        NaN
3041511        ?          NaN        NaN
3047395        ?          NaN        NaN
3047962        ?          NaN        NaN
3050730        ?          NaN        NaN
3059015        ?          NaN        NaN
3067738        -          NaN        NaN
3071016        ?          NaN        NaN
3130387     none      en:none        NaN
3144294      NaN      en:none        NaN
3262111        ?          NaN        NaN
3276588        ?          NaN        NaN
3292165        -          NaN        NaN
3461282        ?          NaN        NaN
3480357        ?          NaN        NaN
3539963        -          NaN        NaN
3541469        -          NaN        NaN
3626514        -          NaN        NaN
3812799      ???          NaN        NaN
3872053       ^^          NaN        NaN
4149196        -          NaN        NaN
4195390        ?          NaN        NaN
4209366        ?          NaN        NaN
4241042        ?          NaN        NaN
4366657        ?          NaN        NaN
4383444        -          NaN        NaN
4401193        ?          NaN        NaN
4402068        ?          NaN        NaN
4450914        ?          NaN        NaN
4499927      NaN      en:none        NaN

In [18]:
drop_col = ["origins", "origins_tags"]

df = df.drop(columns=drop_col)

In [19]:
spalten_info = pd.DataFrame({"Anzahl Einträge": df.count(), "Einzigartige Werte": df.nunique(), "Datentyp": df.dtypes})
spalten_info["Anzahl Duplikate"] = spalten_info["Anzahl Einträge"] - spalten_info["Einzigartige Werte"]
pd.set_option("display.width", 1000)
pd.set_option("display.max_rows", None)

print(spalten_info)

                  Anzahl Einträge  Einzigartige Werte Datentyp  Anzahl Duplikate
product_name              4169122             2617310   object           1551812
quantity                  1431579               74000   object           1357579
origins_en                 172496               19274   object            153222
cities                          1                   1   object                 0
cities_tags                101856                8762   object             93094
traces                     171517               16777   object            154740
traces_tags                233527               16950   object            216577
traces_en                  228341               16947   object            211394
serving_size              1428571              129654   object           1298917
serving_quantity          1407807                6721   object           1401086
product_quantity          1377387                6708   object           1370679

In [20]:
temp = ["cities", "cities_tags"]

print(df[temp].dropna().sample())

                                                    cities                                        cities_tags
1995507  en:to-be-completed, en:nutrition-facts-complet...  en:to-be-completed,en:nutrition-facts-complete...

In [21]:
df["cities_tags"].value_counts().head(200)

cities_tags
sable-sur-sarthe-sarthe-france                                                       1332
theix-morbihan-france                                                                 608
corbas-rhone-france                                                                   597
saint-evarzec-finistere-france                                                        538
nueil-les-aubiers-deux-sevres-france                                                  533
kervignac-morbihan-france                                                             514
chateaubourg-ille-et-vilaine-france                                                   508
boulogne-sur-mer-pas-de-calais-france                                                 505
douarnenez-finistere-france                                                           468
villers-bocage-calvados-france                                                        465
saint-geours-de-maremne-landes-france                                                 442
mans-sarthe-france                                                                    430
vitre-ille-et-vilaine-france                                                          415
estillac-lot-et-garonne-france                                                        372
quiberon-morbihan-france                                                              364
saint-martin-des-entrees-calvados-france                                              352
cavalerie-aveyron-france                                                              351
collinee-cotes-d-armor-france                                                         348
saint-fulgent-vendee-france                                                           347
lamballe-cotes-d-armor-france                                                         345
avignon-vaucluse-france                                                               344
plouedern-finistere-france                                                            338
pouzauges-vendee-france                                                               338
saint-denis-de-l-hotel-loiret-france                                                  319
chapelle-d-andaine-orne-france                                                        310
quimper-finistere-france                                                              310
vieil-moutier-pas-de-calais-france                                                    298
gouvieux-oise-france                                                                  293
mouilleron-en-pareds-vendee-france                                                    292
clermont-ferrand-puy-de-dome-france                                                   291
loudeac-cotes-d-armor-france                                                          291
bannalec-finistere-france,bannalec-finistere-france                                   285
libercourt-pas-de-calais-france                                                       284
cholet-maine-et-loire-france                                                          283
bannalec-finistere-france                                                             273
chantonnay-vendee-france                                                              268
sourn-morbihan-france                                                                 264
castelnaudary-aude-france                                                             261
saint-gilles-croix-de-vie-vendee-france                                               260
avoudrey-doubs-france                                                                 260
obernai-bas-rhin-france                                                               256
roquefort-sur-soulzon-aveyron-france                                                  251
ferrieres-en-bray-seine-maritime-france                                               248
saint-germain-des-fosses-allier-france                                                241
ars-sur-moselle-moselle-france                                                        237
chavagnes-en-paillers-vendee-france                                                   236
cherre-sarthe-france                                                                  228
sable-sur-sarthe-sarthe-france,sable-sur-sarthe-sarthe-france                         224
poligny-jura-france                                                                   220
villers-bocage-calvados-france,villers-bocage-calvados-france                         215
plouvien-finistere-france                                                             214
troarn-calvados-france                                                                213
sarre-union-bas-rhin-france                                                           211
aubagne-bouches-du-rhone-france                                                       210
chailley-yonne-france                                                                 208
brive-la-gaillarde-correze-france                                                     201
villeneuve-d-ascq-nord-france                                                         200
saint-esteve-pyrenees-orientales-france                                               200
segre-maine-et-loire-france                                                           196
sottevast-manche-france                                                               196
saint-pol-sur-ternoise-pas-de-calais-france                                           195
saint-medard-d-eyrans-gironde-france                                                  194
ancenis-loire-atlantique-france                                                       194
jouy-yonne-france                                                                     192
guer-morbihan-france                                                                  189
bazoche-gouet-eure-et-loir-france                                                     188
aoste-isere-france,aoste-isere-france                                                 187
plabennec-finistere-france                                                            185
saint-malo-ille-et-vilaine-france                                                     183
plelo-cotes-d-armor-france                                                            182
essarts-vendee-france                                                                 181
pouldreuzic-finistere-france                                                          180
baud-morbihan-france                                                                  179
ceyzeriat-ain-france                                                                  178
mordelles-ille-et-vilaine-france                                                      178
saint-agathon-cotes-d-armor-france                                                    177
conde-sur-vire-manche-france                                                          176
saint-christol-les-ales-gard-france                                                   176
gace-orne-france                                                                      176
chambery-savoie-france                                                                175
virazeil-lot-et-garonne-france                                                        173
perpignan-pyrenees-orientales-france                                                  172
lacaune-tarn-france                                                                   170
chef-du-pont-manche-france                                                            169
yffiniac-cotes-d-armor-france                                                         168
monteux-vaucluse-france                                                               167
charmes-sur-rhone-ardeche-france                                                      166
feillens-ain-france                                                                   166
camaret-sur-aigues-vaucluse-france                                                    166
ars-sur-moselle-moselle-france,ars-sur-moselle-moselle-france                         165
quimperle-finistere-france                                                            165
biars-sur-cere-lot-france                                                             165
moreac-morbihan-france                                                                164
havre-seine-maritime-france                                                           163
concarneau-finistere-france                                                           163
lamballe-cotes-d-armor-france,lamballe-cotes-d-armor-france                           163
tilloy-les-mofflaines-pas-de-calais-france                                            162
talaudiere-loire-france                                                               162
maubourguet-hautes-pyrenees-france                                                    162
lessay-manche-france                                                                  162
saint-gerand-morbihan-france                                                          162
moneteau-yonne-france                                                                 162
mazamet-tarn-france                                                                   161
saint-martin-d-abbat-loiret-france                                                    161
rosporden-finistere-france                                                            161
sceaux-sur-huisne-sarthe-france                                                       161
limoges-haute-vienne-france                                                           160
antony-hauts-de-seine-france                                                          159
bressuire-deux-sevres-france                                                          159
rungis-val-de-marne-france                                                            159
vallieres-haute-savoie-france                                                         157
saint-philibert-morbihan-france                                                       155
villers-bocage-somme-france                                                           154
connerre-sarthe-france                                                                153
bignan-morbihan-france                                                                152
faverolles-somme-france                                                               151
hesdin-l-abbe-pas-de-calais-france                                                    151
montayral-lot-et-garonne-france                                                       150
plouay-morbihan-france                                                                150
vallet-loire-atlantique-france                                                        150
sainte-hermine-vendee-france                                                          150
romans-sur-isere-drome-france                                                         149
saint-martin-des-entrees-calvados-france,saint-martin-des-entrees-calvados-france     148
motte-servolex-savoie-france                                                          148
dijon-cote-d-or-france                                                                148
feytiat-haute-vienne-france                                                           148
toulouse-haute-garonne-france                                                         146
bonloc-pyrenees-atlantiques-france                                                    146
cleron-doubs-france                                                                   146
machecoul-loire-atlantique-france                                                     146
plougasnou-finistere-france                                                           145
hoerdt-bas-rhin-france                                                                145
wimille-pas-de-calais-france                                                          145
tourcoing-nord-france                                                                 145
aoste-isere-france                                                                    143
lons-le-saunier-jura-france                                                           143
ploumagoar-cotes-d-armor-france                                                       142
malemort-sur-correze-correze-france                                                   142
verdun-meuse-france                                                                   141
tain-l-hermitage-drome-france                                                         140
illkirch-graffenstaden-bas-rhin-france                                                140
rians-cher-france                                                                     139
port-saint-louis-du-rhone-bouches-du-rhone-france                                     139
blanquefort-gers-france                                                               138
espaly-saint-marcel-haute-loire-france                                                138
carentan-manche-france                                                                137
brignais-rhone-france                                                                 137
montauban-tarn-et-garonne-france                                                      137
couchey-cote-d-or-france                                                              136
locoal-mendon-morbihan-france                                                         136
thouars-deux-sevres-france                                                            134
livarot-calvados-france                                                               134
loue-sarthe-france                                                                    134
marges-drome-france                                                                   132
vitrolles-bouches-du-rhone-france                                                     130
liffre-ille-et-vilaine-france                                                         129
saint-jean-de-beugne-vendee-france                                                    128
ploudaniel-finistere-france                                                           127
saint-paul-en-jarez-loire-france                                                      126
saint-just-chaleyssin-isere-france                                                    125
saint-pere-en-retz-loire-atlantique-france                                            125
ivry-sur-seine-val-de-marne-france                                                    125
noironte-doubs-france                                                                 124
saint-meen-le-grand-ille-et-vilaine-france                                            124
chambly-oise-france                                                                   123
luche-pringe-sarthe-france                                                            122
cuincy-nord-france                                                                    121
malville-loire-atlantique-france                                                      120
lubersac-correze-france                                                               120
saint-pierre-du-mont-landes-france                                                    120
capdenac-gare-aveyron-france                                                          119
apremont-vendee-france                                                                118
molay-littry-calvados-france                                                          117
isle-sur-la-sorgue-vaucluse-france                                                    117
vieille-brioude-haute-loire-france                                                    117
chalon-sur-saone-saone-et-loire-france                                                117
noyal-sur-vilaine-ille-et-vilaine-france                                              116
bazas-gironde-france                                                                  116
evron-mayenne-france                                                                  116
falaise-calvados-france                                                               116
saint-gilles-croix-de-vie-vendee-france,saint-gilles-croix-de-vie-vendee-france       115
saint-denis-la-chevasse-vendee-france                                                 114
montfermeil-seine-saint-denis-france                                                  113
vienne-isere-france                                                                   113
rennes-ille-et-vilaine-france                                                         113
saint-mars-la-jaille-loire-atlantique-france                                          113
bailleul-nord-france                                                                  112
raismes-nord-france                                                                   111
figeac-lot-france                                                                     111
boisgervilly-ille-et-vilaine-france                                                   110
binic-cotes-d-armor-france                                                            110
avignon-vaucluse-france,avignon-vaucluse-france                                       108
mably-loire-france                                                                    108
merville-nord-france                                                                  107
saint-symphorien-sur-coise-rhone-france                                               107
saint-just-de-claix-isere-france                                                      106
bourg-en-bresse-ain-france                                                            106
briec-finistere-france                                                                106
paris-9e-arrondissement-paris-france                                                  105
montigny-lengrain-aisne-france                                                        105
Name: count, dtype: int64

In [22]:
vergleich = df.dropna(subset=["cities", "cities_tags"])

vergleich["cities"].equals(vergleich["cities_tags"])

pd.set_option("display.max_colwidth", None)

print(df["cities"].dropna())

1995507    en:to-be-completed, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:origins-completed, en:categories-completed, en:brands-completed, en:packaging-to-be-completed, en:quantity-completed, en:product-name-completed, en:photos-validated, en:packaging-photo-selected, en:nutrition-photo-selected, en:ingredients-photo-selected, en:front-photo-selected, en:photos-uploaded
Name: cities, dtype: object

In [23]:
df.loc[1995507, "cities_tags"]

'en:to-be-completed,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:packaging-code-to-be-completed,en:characteristics-to-be-completed,en:origins-completed,en:categories-completed,en:brands-completed,en:packaging-to-be-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:packaging-photo-selected,en:nutrition-photo-selected,en:ingredients-photo-selected,en:front-photo-selected,en:photos-uploaded'

In [24]:
df = df.drop(columns="cities")

In [25]:
spalten_info = pd.DataFrame({"Anzahl Einträge": df.count(), "Einzigartige Werte": df.nunique(), "Datentyp": df.dtypes})
spalten_info["Anzahl Duplikate"] = spalten_info["Anzahl Einträge"] - spalten_info["Einzigartige Werte"]
pd.set_option("display.width", 1000)
pd.set_option("display.max_rows", None)

print(spalten_info)

                  Anzahl Einträge  Einzigartige Werte Datentyp  Anzahl Duplikate
product_name              4169122             2617310   object           1551812
quantity                  1431579               74000   object           1357579
origins_en                 172496               19274   object            153222
cities_tags                101856                8762   object             93094
traces                     171517               16777   object            154740
traces_tags                233527               16950   object            216577
traces_en                  228341               16947   object            211394
serving_size              1428571              129654   object           1298917
serving_quantity          1407807                6721   object           1401086
product_quantity          1377387                6708   object           1370679

In [26]:
col = "cities_tags"
suchwort = "france"

anzahl = df[col].str.contains(suchwort, case=False, na=True)

neu = df[~anzahl]

print(neu)

                                 product_name                                                                        quantity origins_en                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cities_tags traces traces_tags             traces_en                    serving_size             serving_quantity product_quantity
1995507  Tofu Épeautre, butternut, châtaignes  en:wine-vinegar,en:vinegar,en:cooked-grape-must,en:fruit,en:must,en:grape-must        NaN  en:to-be-completed,en:nutrition-facts-completed,en:ingredients-completed,en:expiration-date-to-be-completed,en:packaging-code-to-be-completed,en:characteristics-to-be-completed,en:origins-completed,en:categories-completed,en:brands-completed,en:packaging-to-be-completed,en:quantity-completed,en:product-name-completed,en:photos-validated,en:packaging-photo-selected,en:nutrition-photo-selected,en:ingredients-photo-selected,en:front-photo-selected,en:photos-uploaded    0.8  1644749437  2022-02-13T10:50:37Z  en:balsamic-vinegars-of-modena  Balsamic vinegars of Modena              NaN

In [27]:
pd.reset_option("all")

temp = ["traces", "traces_tags", "traces_en"]

print(df[temp].dropna().sample(30))

C:\Users\De\AppData\Local\Temp\ipykernel_10032\4171937974.py:1: FutureWarning: data_manager option is deprecated and will be removed in a future version. Only the BlockManager will be available.
  pd.reset_option("all")
C:\Users\De\AppData\Local\Temp\ipykernel_10032\4171937974.py:1: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
  pd.reset_option("all")

                                                    traces  \
1995251                                    en:milk,en:nuts
4299055                          en:eggs,en:gluten,en:milk
4360903                                          en:gluten
2889874                                            en:nuts
3745554  en:eggs,en:milk,en:mustard,en:sesame-seeds,en:...
1870754                                        en:soybeans
2648275  en:celery,en:mustard,en:nuts,en:sesame-seeds,e...
2540367                                            en:nuts
1829238                                            en:milk
2292994                                            en:nuts
1998504                             en:mustard,en:soybeans
2622081   en:eggs,en:gluten,en:nuts,en:peanuts,en:soybeans
3607434                                en:eggs,en:soybeans
1870206                          en:gluten,en:sesame-seeds
2177451                                    en:fish,en:nuts
1763876                                            en:nuts
3189275                                  en:gluten,en:milk
1856435                                            en:milk
2894659                            en:nuts,en:sesame-seeds
3367678                                            en:nuts
2059689                                          en:gluten
2997448                   en:sulphur-dioxide-and-sulphites
2831894                         el:ίχνη άλλων ξηρών καρπών
1397670                     en:eggs,en:mustard,en:soybeans
2034639                                            en:nuts
2389847                                            en:milk
3494006           en:gluten,en:peanuts,en:Arachides,en:Blé
1292433                                            en:milk
4096560                                    en:eggs,en:nuts
3098645                                    en:milk,en:nuts

                                               traces_tags  \
1995251                                    en:milk,en:nuts
4299055                          en:eggs,en:gluten,en:milk
4360903                                          en:gluten
2889874                                            en:nuts
3745554  en:eggs,en:milk,en:mustard,en:sesame-seeds,en:...
1870754                                        en:soybeans
2648275  en:celery,en:mustard,en:nuts,en:sesame-seeds,e...
2540367                                            en:nuts
1829238                                            en:milk
2292994                                            en:nuts
1998504                             en:mustard,en:soybeans
2622081   en:eggs,en:gluten,en:nuts,en:peanuts,en:soybeans
3607434                                en:eggs,en:soybeans
1870206                          en:gluten,en:sesame-seeds
2177451                                    en:fish,en:nuts
1763876                                            en:nuts
3189275                                  en:gluten,en:milk
1856435                                            en:milk
2894659                            en:nuts,en:sesame-seeds
3367678                                            en:nuts
2059689                                          en:gluten
2997448                   en:sulphur-dioxide-and-sulphites
2831894                         el:ίχνη-άλλων-ξηρών-καρπών
1397670                     en:eggs,en:mustard,en:soybeans
2034639                                            en:nuts
2389847                                            en:milk
3494006           en:gluten,en:peanuts,en:arachides,en:ble
1292433                                            en:milk
4096560                                    en:eggs,en:nuts
3098645                                    en:milk,en:nuts

                                         traces_en
1995251                                  Milk,Nuts
4299055                           Eggs,Gluten,Milk
4360903                                     Gluten
2889874                                       Nuts
3745554    Eggs,Milk,Mustard,Sesame seeds,Soybeans
1870754                                   Soybeans
2648275  Celery,Mustard,Nuts,Sesame seeds,Soybeans
2540367                                       Nuts
1829238                                       Milk
2292994                                       Nuts
1998504                           Mustard,Soybeans
2622081          Eggs,Gluten,Nuts,Peanuts,Soybeans
3607434                              Eggs,Soybeans
1870206                        Gluten,Sesame seeds
2177451                                  Fish,Nuts
1763876                                       Nuts
3189275                                Gluten,Milk
1856435                                       Milk
2894659                          Nuts,Sesame seeds
3367678                                       Nuts
2059689                                     Gluten
2997448              Sulphur dioxide and sulphites
2831894                 el:ίχνη-άλλων-ξηρών-καρπών
1397670                      Eggs,Mustard,Soybeans
2034639                                       Nuts
2389847                                       Milk
3494006               Gluten,Peanuts,Arachides,Ble
1292433                                       Milk
4096560                                  Eggs,Nuts
3098645                                  Milk,Nuts

In [28]:
s1 = "traces"
s2 = "traces_tags"
s3= "traces_en"

b1 = df[s1].isna()
b2 = df[s2].notna()
b3 = df[s3].notna()

anzahl = (b1 & (b2 | b3)).sum()

print(anzahl)

62010

In [29]:
anzahl = (df["traces"] == df["traces_tags"]).sum()

print(anzahl)

154280

In [30]:
filter1 = (df["traces"] != df["traces_tags"])
filter2 = (df["traces"].isna() & df["traces_tags"].isna())
temp = df[filter1 & ~filter2]
cols = ["traces", "traces_tags"]

print(temp[cols])

                                                    traces  \
18       en:crustaceans,en:fish,en:gluten,en:molluscs,e...
26                                                     NaN
103                                         en:gluten free
296                                              fr:Avocat
388                                      en:Lechesingluten
...                                                    ...
4500539                                                NaN
4501166                                                NaN
4501301                                                NaN
4501304                                                NaN
4501328                                                NaN

                                               traces_tags
18       en:crustaceans,en:fish,en:gluten,en:molluscs,e...
26                                                 en:nuts
103                                         en:gluten-free
296                                              fr:avocat
388                                      en:lechesingluten
...                                                    ...
4500539                       en:gluten,en:nuts,en:peanuts
4501166                        en:sesame-seeds,en:soybeans
4501301                          en:eggs,en:gluten,en:nuts
4501304                      en:gluten,en:nuts,en:soybeans
4501328                                    en:sesame-seeds

[79247 rows x 2 columns]

In [31]:
s1 = "traces_tags"
s2 = "traces_en"

b1 = df[s1].isna()
b2 = df[s2].notna()

anzahl = (b1 & b2).sum()

print(anzahl)

0

In [32]:
df["traces"] = df["traces"].fillna(df["traces_tags"]).fillna(df["traces_en"])

drop_col = ["traces_tags", "traces_en"]

df = df.drop(columns=drop_col)

In [33]:
spalten_info = pd.DataFrame({"Anzahl Einträge": df.count(), "Einzigartige Werte": df.nunique(), "Datentyp": df.dtypes})
spalten_info["Anzahl Duplikate"] = spalten_info["Anzahl Einträge"] - spalten_info["Einzigartige Werte"]
pd.set_option("display.width", 1000)
pd.set_option("display.max_rows", None)

print(spalten_info)

                  Anzahl Einträge  Einzigartige Werte Datentyp  Anzahl Duplikate
product_name              4169122             2617310   object           1551812
quantity                  1431579               74000   object           1357579
origins_en                 172496               19274   object            153222
cities_tags                101856                8762   object             93094
traces                     233527               17729   object            215798
serving_size              1428571              129654   object           1298917
serving_quantity          1407807                6721   object           1401086
product_quantity          1377387                6708   object           1370679

In [34]:
cols = ["quantity", "serving_size", "serving_quantity", "product_quantity"]

df[cols].dropna().sample(100)

                   quantity                                       serving_size serving_quantity product_quantity
3036368            400 gram                                            10 gram             10.0            400.0
217383                18 oz                                      1 Tbsp (20 g)             20.0       510.291416
1305473                400g                                               100g            100.0            400.0
996780      7.05 oz (200 g)                                       1 bun (50 g)             50.0       199.864138
4301305               150 g                                               20 g             20.0            150.0
1169147                90 g                                               100g            100.0             90.0
135976                 24 g                                                24g             24.0             24.0
3812529                50 g                                               50 g             50.0             50.0
3343818                  1L                                  1 serving (330 g)            330.0           1000.0
717080                 120g                                    0.5 pack (60 g)             60.0            120.0
4293633                1 kg                                                45g             45.0           1000.0
3897637               216 g                                                9 g              9.0            216.0
1111978               958 g                                 1 portion (240 ml)            240.0            958.0
3871022                99 g                                                99g             99.0             99.0
128700                 28 g                                28.000000000000004g             28.0             28.0
130961                130 g                                  1 portion (130 g)            130.0            130.0
1376661               125 g                                              125 g            125.0            125.0
390631         12 OZ (340g)                                               113g            113.0       340.194277
3450385               160 g                                               160g            160.0            160.0
4414379                130g                                                20g             20.0            130.0
1730667              120 ml                                             100 ml            100.0            120.0
2042687                1 kg                                              125 g            125.0           1000.0
3307198            16 fl oz                               473.17599999999993mL          473.176          473.176
4409183                375g                                                 6g              6.0            375.0
1434266            100 gram                                           100 gram            100.0            100.0
1054664            12 fl oz                                           12 fl oz          354.882          354.882
3559064                 40g                                               40 g             40.0             40.0
242634               237 ml                                236.58799999999997g          236.588            237.0
2032855             0.37 kg                                      370 g (370 g)            370.0            370.0
4295650               320ml                                  1 BOTTLE (320 ml)            320.0            320.0
3016650               200 g  20 g (Cet emballage contient environ 10 portio...             20.0            200.0
4303625                17 g                                               17 g             17.0             17.0
2809284              330 ML                                              330ml            330.0            330.0
175292                 28 g                                28.000000000000004g             28.0             28.0
1269707      240 g (6 x 40)                                               40 g             40.0            240.0
1898653               750 g                                               100g            100.0            750.0
1202146               541 g                                               541g            541.0            541.0
1794595               240 g                                               240g            240.0            240.0
576906                  45g                                               100g            100.0             45.0
194511                140 g                                               140g            140.0            140.0
373668                16 oz                                   1 portion (35 g)             35.0        453.59237
1155924                3 oz                                       1 can (85 g)             85.0        85.048569
1243083        1 serving(s)                                               100g            100.0              0.0
1996026                 1 l                                              250ml              250           1000.0
3415092                40 g                                        40 g (40 g)             40.0             40.0
3093219               500 g                                               19 g             19.0            500.0
2647764                 125                                              100 g            100.0              0.0
1201283        1 serving(s)                                               100g            100.0              0.0
1799565             600 g e                                    Un sachet 200 g            200.0            600.0
1864896  1 kg e (250 * 4 g)                                                4 g              4.0           1000.0
2274377                 60g                                   1 portion (60 g)             60.0             60.0
3542981                125g                                              125 g            125.0            125.0
3054471               160 g                                               20 g             20.0            160.0
1323349                400g                                      2 tbsp (37 g)             37.0            400.0
2444420                235g                                               100g            100.0            235.0
1843701        1 serving(s)                                               100g            100.0              0.0
3901239              1000 g                                              1000g           1000.0           1000.0
2888640               360 g                                   1 serving (45 g)             45.0            360.0
837745                737 g                                      1 tbsp (15 g)             15.0            737.0
1173898               40 oz                                   1 portion (28 g)             28.0      1133.980925
3145788                300g                                               15 g             15.0            300.0
3169230              250 ml                                               100g            100.0            250.0
2997641               200gr                                               100g            100.0            200.0
1084671                9 oz                                     1 bowl (255 g)            255.0       255.145708
1730399               175 g       40 g (Ce sachet contient environ 4 portions)             40.0            175.0
2258854               200 g                                  1 portion (100 g)            100.0            200.0
3436601                100g                                                30g             30.0            100.0
3343415               400 g                                             100.0g            100.0            400.0
1719856               250 g                                              250 g            250.0            250.0
4247374             19 gram                                              100 g            100.0             19.0
2039856             0.12 kg                                                30g             30.0            120.0
1703107               70 cl                                             100 ml            100.0            700.0
1753425               250 g                                              125 g            125.0            250.0
2599348        1 serving(s)                                               100g            100.0              0.0
1660623               140 g                                             140.0g            140.0            140.0
497360                700 g                                6 g / 1 c. à table               6.0            700.0
3575939                500g                                               80gm             80.0            500.0
4116192               400 g                                               25 g             25.0            400.0
3581938                500g                                                60g             60.0            500.0
3446989                40 g                                               40 g             40.0             40.0
1778007               400 g                                              100 g            100.0            400.0
2775892              287.7g                                              100 g            100.0            287.7
4233564           1000 gram                                           100 gram            100.0           1000.0
40574                240 ml                                236.58799999999997g          236.588            240.0
2673378                95 г                                                 7g              7.0             95.0
1060806              20x90g                                     1 POUCH (90 g)             90.0           1800.0
2451931               110 g                                               110g            110.0            110.0
1113800                8 oz                                       2 onz (56 g)             56.0       226.796185
2893270        1 serving(s)                                               100g            100.0              0.0
1840248               380 g                                              190 g            190.0            380.0
2768252                56 g                                               4.0g              4.0             56.0
1112477               454 g                                               85 g             85.0            454.0
2810018                560g                                                45g             45.0            560.0
3516673        1 serving(s)                                               100g            100.0              0.0
478682                250 g                                                80g             80.0            250.0
3340121               170 g                                              170 g            170.0            170.0
3510147                84 g                                              3.5 g              3.5             84.0
2421793            6 x 52 g                                              52.0g             52.0            312.0
3136427               415 g                                                30g             30.0            415.0
1665795               180 g                                               25 g             25.0            180.0

In [35]:
s1 = "quantity"
s2 = "product_quantity"

b1 = df[s2].isna()
b2 = df[s1].notna()

anzahl = (b1 & b2).sum()

print(anzahl)

54210

In [36]:
print(df["product_quantity"].apply(type).value_counts())

product_quantity
<class 'float'>    4496265
<class 'str'>         5092
Name: count, dtype: int64

In [38]:
b1 = df["product_quantity"].apply(type) == str

set = df[b1]

# Zum schauen, ob Strings aus Zahlen bestehen oder Fehlerhaft sind

In [39]:
s1 = "quantity"
s2 = "product_quantity"

b1 = df[s2].isna()
b2 = df[s1].notna()

filter = (b1 & b2)

set = df[filter]

print(set["quantity"].sample(10))

2876194    200 Tabletten
515176          3 bulbs,
2487249             1pcs
2442455       490unknown
4396387             1pcs
2308339              300
1197842              360
1782432           10 pcs
3146103              160
2991336              450
Name: quantity, dtype: object

In [40]:
print(df["serving_quantity"].apply(type).value_counts())

serving_quantity
<class 'float'>    4499144
<class 'str'>         2213
Name: count, dtype: int64

In [41]:
s1 = "serving_quantity"
s2 = "serving_size"

b1 = df[s1].isna()
b2 = df[s2].notna()

anzahl = (b1 & b2).sum()

print(anzahl)

20777

In [42]:
s1 = "serving_quantity"
s2 = "serving_size"

b1 = df[s1].isna()
b2 = df[s2].notna()

filter = (b1 & b2)

set = df[filter]
    
print(set["serving_size"].sample(100))

1147591                        0.667 cup (0.667 cup)
542540                                           100
3306883                                       2 Tbsp
4030406                                           25
54117                            0.25 cup (0.25 cup)
1160505                                1 cup (1 cup)
4136344                                           22
1719736                                    190     g
513459                                            60
2963430                                         24,3
808591                                         1 egg
2758915                                           24
621068                         0.667 cup (0.667 cup)
2392887                                          250
348643                                             1
2869710                                      serving
221086                                        2 tbsp
1872451                                   3 macarons
3298804                                          750
2233546                                    3 capsues
1185085                          0.66 cup (0.66 cup)
3171892                                       1 vEGG
1335357                                          260
2739995                                          100
1070084                      2 capsules (2 capsules)
2805601                                            1
2922749                                           45
1285348                                      serving
3488068                                           17
2378140                                        1.373
1106404                              1 tbsp (1 tbsp)
788409                             1.0 can (1.0 can)
2038328                                      serving
3187083                                          100
541247                                            75
560473                               2 tbsp (2 tbsp)
1049419                              1 tbsp (1 tbsp)
3097347                                           85
2589577                                           46
3141696                                          330
1081170                                  1 container
2814730                                          750
98131                                  1 tsp (1 tsp)
555483                                         1 tbs
4412                                       2 Gummies
3157197                                           25
124252                                  1 Gummy Bear
750305                                      1 packet
367853                             1 portion (1 cup)
2494019                                           40
2472817                                          300
2395316                                           50
1252432                                      serving
1022205                         1 portion (1.75 cup)
363203                           0.25 cup (0.25 cup)
950586                                            30
3258482                                           36
649732                           1.25 cup (1.25 cup)
848556                                    1 tortilla
3464821                                           10
1072774                        1 portion (1 portion)
93078                                             34
870466                                1 g (0.25 tsp)
998526                         1 capsule (1 capsule)
1254646                                 1 quesadilla
2123573                                          115
805183                               3 tbsp (3 tbsp)
2420067                                          100
963833                               2 tbsp (2 tbsp)
140452                          1 portion (0.25 cup)
2419486                                           30
2577459                                          420
360294                           0.33 cup (0.33 cup)
1090628                        1 portion (1 portion)
1708781                                            0
1023175                                          140
1141970                                     4 pieces
1989949                           4 carrés (~28,6 g)
4332869                                           70
4139381                                         12.5
1108272                                 85 g (1 BAR)
944202     1 vegetable capsule (1 vegetable capsule)
3066130                                          250
6756                                          1 tbsp
124917                                             2
2847798                        1 capsule (1 capsule)
2332356                                      serving
1434781                                        1 cup
1123453                                14 g (1 Tbsp)
1373476                                         demi
1085312                        1 portion (1 portion)
3137624                                            1
1099854                              3 1 (0.667 cup)
1881990                                      serving
4332796                                           gf
1054644                                1 can (1 can)
2278594                                            1
1459785                     20 spedmogeljk na ankoop
403990                          1 portion (0.25 cup)
384340                                       1/2 cup
Name: serving_size, dtype: object

In [43]:
drop_col = ["quantity", "serving_size"]

df = df.drop(columns=drop_col)

In [44]:
spalten_info = pd.DataFrame({"Anzahl Einträge": df.count(), "Einzigartige Werte": df.nunique(), "Datentyp": df.dtypes})
spalten_info["Anzahl Duplikate"] = spalten_info["Anzahl Einträge"] - spalten_info["Einzigartige Werte"]
pd.set_option("display.width", 1000)
pd.set_option("display.max_rows", None)

print(spalten_info)

                  Anzahl Einträge  Einzigartige Werte Datentyp  Anzahl Duplikate
product_name              4169122             2617310   object           1551812
origins_en                 172496               19274   object            153222
cities_tags                101856                8762   object             93094
traces                     233527               17729   object            215798
serving_quantity          1407807                6721   object           1401086
product_quantity          1377387                6708   object           1370679